insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Pearl Peeler','vtoigpu@gmail.com','e94f9eeb4f390f4b',7226844652,'l y n d j j g a l z','j j x y v y x z z i',909919,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('James Scruggs','mlqoceu@gmail.com','f8d27c051ddeb220',6208803368,'c b n b c w a x a x','g e t b x f t o b a',718726,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Norman Zuleger','ctcfodh@gmail.com','29816fb408ba72d9',7318240593,'l b t i r a z h m t','b z u n d l b x s x',472651,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Curt Miller','mvuhelk@gmail.com','ca5f90f21e8f63cd',6286852463,'o j p s a g g l o k','p t w l h y t q p x',789928,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Patricia Ahrens','emhfyao@gmail.com','cda1ac6a5dd3f396',4975179408,'a w q b n w a n d i','a m g b n z e s v r',834603,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Bruce Frame','kfamtjr@gmail.com','a18d67ac27b34832',7082679368,'k q g f m x x y b r','c l v f k z i u p v',362634,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Scott Arnette','ytqypdm@gmail.com','4c71655e9c8d5274',9518081630,'n o z j s z t e o h','m w g l s e e g s m',417385,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Deb Guzman','onkxbat@gmail.com','7534b20ac87146fc',4145317950,'z q i b x b l j a h','w f c z e e c k i r',758013,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Anthony Robinson','inapkcb@gmail.com','d02da873cc7a09dd',3080008381,'l a t d o j l m o q','l e z k v l k t p f',679395,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Martin Moniz','aiibxys@gmail.com','ddf478198830855e',5189083907,'d u h m q r d t y k','o o l i v d v a d i',449650,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Albert Elledge','iapddra@gmail.com','14750d26259b9dba',3066259055,'y n n b t h w s u k','h q t j d x p v r l',390745,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Thelma Emmett','xgebpss@gmail.com','f9dac05d82869d6b',7793633583,'u v e a z i q h u q','f y x j x h m i l w',938574,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Ben Peters','pjvqlnb@gmail.com','982a5b06731ac985',6240808357,'h o x l a k y e w k','x b e u g x l m a j',622159,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Deborah Norville','mgapfse@gmail.com','6f3d4f407e17ac27',7955289359,'m n x y p q s q v s','s k g s q a a g l c',868735,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Raymond Strickler','mhtwptc@gmail.com','9af186cb08571c6b',9925295718,'u f y x i o x l t e','x e u r i l i e i b',869886,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Michelle Myers','gobksgb@gmail.com','44e887d0f002bfcc',8117535555,'k l v j a e o k r b','q v z g j r e e m u',288149,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Foster Nguyen','opxvlnq@gmail.com','7c1b9f079155e80f',5093555966,'h u h h o m m r x n','f g a m i a w a z z',390395,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Clyde Hedden','jpbyoay@gmail.com','76643cb59069e055',1234414307,'d u s n i w s s e j','m x b i z m j q a k',566471,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Roger Tomas','ijrsboc@gmail.com','5859da7163aba529',9170500641,'x r b z r u h w g c','w f c o x d s x e v',493826,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Gene Gooden','uxqbnnc@gmail.com','54e5cebe0ca0c87d',4651525792,'b j j h p b i l o r','f r f c v y i n l o',161318,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Paula Spease','dclnkei@gmail.com','df8a3b9e5a2d0fc1',7432426121,'y c r b x v f e i r','c d d j b j z s a m',576809,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('David Glatt','kniujkp@gmail.com','92bf64af2bd380ba',5853458941,'l n k g s j g a n w','n p c s o q j j s p',645119,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Debbie Hoyt','gjckxmq@gmail.com','712951e5c5d6d85a',2776537760,'u e f w z y c v q u','q b h d f m j p o t',844959,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Stefanie Cohen','mffvtdt@gmail.com','4d355cf3c32da8fa',2436095176,'h o y b j u l h c g','j g n t r h l m k d',791270,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Christian Bryce','pbdqwkz@gmail.com','6ba83e4e5a6cea01',3589232038,'c f m g q k p n k c','f y q k u w p a l t',109943,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Kristi Gallego','eyjvujc@gmail.com','417fbbab679bc33d',7184108915,'n v s o x t o r d u','d a b s c x p s r q',477165,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Corey Jordan','ononkcw@gmail.com','13d07c1b49291704',3502934365,'h q w a b f i x t v','z b c r s m x p o b',411329,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Erica Gonzalez','jcnyasg@gmail.com','077050fc08dd73d4',6247495551,'l t d l m u k s e s','h z i t r k i z u d',808577,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Janie Smith','wwgjcif@gmail.com','687f84210bb992c5',4788522807,'b y r c z c x j i g','r n s q k y b v x l',989630,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Jaime Rattanasinh','eeeipar@gmail.com','0fb8d9075a68dff8',6142478289,'e n c p a b z v c t','w s s v z b q s h e',459865,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('William Chevere','xdpnnvx@gmail.com','7f9306a68925cc55',9605292263,'h e y l u j s q i p','t a t q q m k h b r',808218,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Yvette Janski','movmoqp@gmail.com','ff1564bc19a4fbc7',4372422130,'r g u w v m o p e w','d n l l s k o n y d',866403,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Blanche Mcmanus','vkimwot@gmail.com','e620e3e4c5163c59',1378477558,'e l r s t t t y i i','i t o d y b n p u i',219775,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Judith Andino','krmcorc@gmail.com','744f6d51d89d418a',2173004984,'d u q m t v o c h m','e h q q t b d j j m',370641,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Jennifer Hamilton','rxqaygf@gmail.com','dec6e246bea67692',2189887592,'t y j y x n d s m i','o i w l i g w x c a',944510,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Autumn Bradley','ndlxlhj@gmail.com','a3555eb89692bd93',2585082407,'j e f j h g x m n w','v w l u s m a v y s',864312,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Alberto Olsen','dpmvutt@gmail.com','28c70326535bc7b4',6631495572,'y r b q m p w z k d','s g b m x z v c a m',229548,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Steven Rosen','pxddzxk@gmail.com','d784372b3d41eacc',2772815670,'z c a d j j s p s c','y x s h e p m r f a',694663,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Robert Johnson','idgcktt@gmail.com','4fc23d248fa5f849',5357369583,'a e f h l w a l w m','w r g l q j h v z u',287250,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Howard Jenkins','fpvtnql@gmail.com','eca10f05dab62891',7263068907,'c z p q b q i f x r','l i p y k p l s q q',665632,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Kip Steward','ydfufue@gmail.com','854e6522fbdd858c',7552106972,'z i p g m j g g w i','o t r q p j f t h h',101391,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Leah Schorn','wnjdtvq@gmail.com','0867b86554169231',6342919902,'l d f x e z a v p v','d o o h p m p g c q',731458,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Tyrell Spalding','wikkejc@gmail.com','af3f6eedb4bde8cd',6538937808,'c m g c s f j r y q','b a e w t b o h z l',186240,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Margaret Goetzinger','monknmq@gmail.com','771bb0a800b110e9',2093978514,'e r p t s h r e v n','q d e f d q a c y a',384757,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Christine Page','ubbwedh@gmail.com','cd7baa46c851107a',9012575524,'q x v w s l t i a s','i h e j x v k f g m',386439,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Jane Tachauer','rifurip@gmail.com','aba6e7043b9b7a2d',1072936570,'e g r j r g x j m q','f o y c d q u b x w',409964,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Geraldine Tobler','emyovnj@gmail.com','bb49cda7596ac743',3388399153,'z z k y z s d i x x','f n f s n v t a q t',202537,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('David Nelms','wqypzpn@gmail.com','4259ed5145da1272',7467841951,'e t g c k c d g m v','d q q d p s e k d u',453562,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Renee Grullon','ccrjtcj@gmail.com','bb9ed6ecc28c6a37',4303098310,'r l m c r p r z q p','k q p h j b w b j h',318248,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Michelle Dreher','qwgopzf@gmail.com','4320ad4dcc407c0b',1867352170,'s m u p x r p d r x','n j o g f g a o t e',577079,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Philip Doyle','snnxnrb@gmail.com','f105348b40eb1c07',6717888582,'s g x c m t s t v f','k k c y d y q n u j',612785,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Alicia Martin','aserpqh@gmail.com','fbd4a9de24520677',4631737797,'t s o q q w e b f r','x v s f x o d b b i',787892,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Betty Kimberlin','rcixxqg@gmail.com','644871e34fa09adc',8420672977,'u q s h a e e e n k','w z o u g n u h g f',910859,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Jean Black','iawvcvc@gmail.com','489361cc63d226bd',1137761508,'c w b z n a s u u w','c x r e z h e t k g',823690,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Teresa Rau','dwgperw@gmail.com','fbe798fc88ca150c',7365903789,'z c y z v j x i x a','x j g d r d p v g p',842619,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Steven Chapell','ehitdgb@gmail.com','39dfae732dbfdef6',4109804367,'i c a t n a n q u c','s h p w c f q s r x',139511,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Roslyn Davia','trmfkdd@gmail.com','b77175b540ff4c09',5934495704,'v e f u j a q d x p','j c q g t u c q h c',984808,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Blanche Crosby','ilpuqgt@gmail.com','7272bb37925d37d7',7922773906,'z z q t f c p t c d','d p m z x g j m d z',771199,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Diane Dooley','llnrsxu@gmail.com','56986f433d29c1b8',1869785483,'n n s z t p f m r v','c d p u l r j p a o',374838,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Betsy Sisk','uefdrqz@gmail.com','0b7f40e043764278',3549382072,'a g x u w f g x o a','b b u g e d h h r l',964656,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Samuel Santos','xufsgfw@gmail.com','d76a16baa2d98dbf',4911242822,'q x d a w h x r p w','m z z h z t o z o a',166102,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Daniel Boling','aebwujo@gmail.com','06403608c9b2e3ee',6258580648,'o x k e r n w r z f','a z j b q l h g g a',677591,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('James Peavey','wdncfbq@gmail.com','547bcfe0418cdcbf',5816712818,'p e g g n l v k q s','l k s y w g f t k s',756624,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Timothy Killinger','wrazsrl@gmail.com','54d4cc69f1e8809c',6812715053,'u h l f r f d g q u','q c t p k j m u g e',899296,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Michael Mitchell','brdiqqw@gmail.com','8cc43447c148d5fa',7916386316,'l s v t p s h g h w','t i e e b y r s i i',654619,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Anthony Boyd','losmofj@gmail.com','4db5839c421c2b82',5053372072,'e g k s n e e t i g','n z o w x a b e i b',759877,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Alice Parra','qxbfjop@gmail.com','dcaffabc262c6a45',3773246235,'m i p g s x p c k m','i k q x b e h u l t',520578,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Joya Wells','ajehuxn@gmail.com','c3e94f7d318d8e91',6448249836,'z w y a m q s w h f','w o e k o u k g i i',626606,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Rodney Hopkins','opkvvlh@gmail.com','d083768fba850dcc',4600208553,'a x o w g e t m r e','j a z r r a i p r f',863105,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Bridget Still','dpursts@gmail.com','bac56482439eff6f',3528695615,'g o x l b j t z i n','n l s p x a h z r u',526082,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Elizabeth Freetage','akuyfzb@gmail.com','a5dce33c9219a5c6',3720224272,'x t c m n v r q o x','o r q y o o p y c m',822224,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Jill Torres','kzlrkhf@gmail.com','013a6e9e75b3f178',6275369880,'d b m a r g b z k g','h h d o e l j q e j',325286,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Chris Martinez','mqdnwei@gmail.com','6a188ccf1d54edd5',4428970805,'h r b d h x u l m t','z j y f r m o l i o',823544,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Christa Verdin','msjktld@gmail.com','2fa34cdd4c873c04',6371059806,'q c l c d c t v y w','c u b i i d j y n z',199841,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Paul Betts','pyjexmk@gmail.com','8cf4d67c72f5c2fe',2796355590,'x x k i k i f r q w','i q j d j s s g v w',847002,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Everett Ankrom','saiwnqo@gmail.com','52bb7398b08f8dfa',8839228845,'y t v i s k f x o g','s v g g n k y d i p',609711,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Derrick Keast','qdvayjm@gmail.com','48f5d67fb23dc723',9817732514,'y o b k j k x v l y','r b q t s z q g i q',711264,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('William Martin','udfkznz@gmail.com','cd9e254ac4974619',1337227787,'h s d q o p y k c g','f r t w i m w r d q',806693,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Janet Thomas','yvtoigl@gmail.com','4fba2ee172cb399f',3231450344,'v e q q y c w g l d','t e m a r y q v i r',345450,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Mario Giordano','xksgemb@gmail.com','955141c2c8282cd2',4861976578,'d l v f j m q i l z','g q h s i t z v y y',496284,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Craig Lafountain','ucdgxow@gmail.com','9c1a3610c46bd808',3317644776,'q q v c l l a j h y','i a b h c h t b c c',550785,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Kenneth Williams','hloxfqw@gmail.com','8ab85e57e485cceb',5482254391,'i x v v m q o d l a','r u a a g o c r r c',373867,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Mario Woodward','jtnspaj@gmail.com','ae0080d6b26d0d91',3832042937,'k b j b s j n n a u','x m s e m g r e u y',631199,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Dan Bagwell','wovsuxh@gmail.com','4f60b4a968b88aa7',2064371102,'y h q l h q l l s y','x w p a c z s l y h',887367,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Kristin Devilbiss','nvmxevm@gmail.com','7b4aee0c34c535dc',2208848452,'d a m y f m a a z r','w w b b g u d b s l',459959,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Susan Morgan','ywpupsy@gmail.com','3749fe7f74af4dbd',5516728408,'q f f c p g f n v c','h b l d n h b u v i',157196,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Richard Deperro','jsqrczp@gmail.com','1398edc59178d67d',9431313899,'r n j s g a a q t a','n p d o u q p j c w',645757,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Deborah Sayles','lsxdewr@gmail.com','68f869882c00e9b2',3022932845,'f j y d e t e m n x','d k j e o q r x o y',281016,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Michelle Roeber','balntae@gmail.com','0ce7fdab25c8035c',5912930681,'x d v r a j c v y i','m d r f j o b f z q',615247,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Joseph Kim','leajepj@gmail.com','14d471e453c2a68c',2710305399,'p k j n n g e a n e','v i o c e c j c u r',119573,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Misty Bryant','srfpfpd@gmail.com','0829416ed9f0bce9',3115928180,'f y p x e f p g o a','q l i a u f z k m o',884224,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Victoria Bell','zxineur@gmail.com','07542301be5beb8f',3469012370,'a j o x l g i w y d','g f m x e v t j z c',315950,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Michael Butler','ivbfaid@gmail.com','a31f4f0172c77499',6226753453,'s y x b f c r m l a','h w g h v x j r s z',465367,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Hye Michaud','dnklulo@gmail.com','49efbd06729d4aad',3465344528,'i m t i y m e l a r','v g g i g g w c r j',113968,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Earl Wilkins','meloorl@gmail.com','915903758f2931a1',8146599200,'p o i j v v f y w c','u u d g v r s l w n',399667,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Joe Michaels','cqaewsd@gmail.com','7b41e2887dfa754c',3026388387,'f d u h k b s y a a','z v j c o x h i k k',277006,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Naomi Welsh','cxaeqkb@gmail.com','3107f27b130ad8e3',4054596539,'j s l k z a j r m e','o v v b s x m p g p',610152,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Larhonda Hendrix','opxwvhc@gmail.com','f99cf5838c54e1ce',3897204846,'j w d i m r i t v s','f p t m n f m f f e',212250,NULL,0);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Lorri Scheidecker','wqrtrss@gmail.com','32023f5b29306a17',1743635520,'u q e r g a l f k y','e k k j c r c g g i',635359,NULL,1);
insert into Accounts(Name,EmailID,Password,PhoneNumber,Address1,Address2,Pincode,SessionID,IsEmployee) values('Deborah Prescott','qeazlmr@gmail.com','5e27d820e9d553d1',2340549249,'u g c q e y g z i m','a o b q z l w l n f',333753,NULL,0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Session(CartValue) values(0);
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('clwidyrdxu',0,0,'gigjyfgvwn');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('rzocupjsdi',0,0,'uaxihrweci');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ffqgeylyyi',0,0,'sossmgyuxa');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('odlfbouedc',0,0,'xviuprvafi');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('nthwfokyca',0,0,'gcbxbnzkhx');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('tyyqiwkkwz',0,0,'tdztecqrkl');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('khpnwkobzq',0,0,'mkomtexrgl');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('iprvtpjuuo',0,0,'ousqpqatgn');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('omzeckpfwj',0,0,'qtswvvjnzp');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('vgfzmjplzj',0,0,'bombrmtsgc');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('saoimmccmt',0,0,'ogvjssrrcj');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('uhbqyswvjl',0,0,'cpesfxdrbe');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ofrwkjlbcl',0,0,'iodjnwhpzv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jodhljgqgy',0,0,'tffcverccs');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('hkzpezcwzr',0,0,'zxzewvcmwc');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('pbfqdztiru',0,0,'staqxdxwia');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('tugdhafncg',0,0,'vrzoxnfcnk');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('izscqplliw',0,0,'fhryibqnht');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('xtuqtterzr',0,0,'rfqeegghnq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('oqhkgnnwtz',0,0,'udcxnikwax');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jhquujrnpk',0,0,'bgtekuizfz');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('qexvkemudc',0,0,'lmwvxbjmyv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('iiwlekuwvc',0,0,'euegnyjmho');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('usiepfhzzr',0,0,'fvnvexoymy');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('enmgstfdky',0,0,'eksxxkfnqs');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ksfagnqcvy',0,0,'epqqrrqkof');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('aetrmwzfvr',0,0,'uhrvryfozj');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jgugvmeede',0,0,'fjeacxtwim');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jzxngxnvhc',0,0,'xrmdlzamlv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('vfjuuaddpd',0,0,'jtgfbpgjny');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('lhnvzgknid',0,0,'hqhveqfwlq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('drieohshrp',0,0,'yckyxxyykt');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ocefxrhkyx',0,0,'fhmnifuwxk');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ynjoxjlinw',0,0,'hvttzhctyq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('vrucvqzclv',0,0,'oyrhvwuhtu');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('nqescmgyhn',0,0,'fowdcvxekq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('hjjhjbehoz',0,0,'vujtnrpxgb');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('esftdozwrb',0,0,'mchepqejko');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('zqsgtgjaga',0,0,'zuxwbfelul');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('psgsdzhjtz',0,0,'reqdditatv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('mvmqxvhxdd',0,0,'yqvpqhzlfe');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('eppimdomyp',0,0,'ihlniuzhkw');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('mpanrevxqk',0,0,'wbrppcoppt');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('bvjfndcnge',0,0,'gilbexcjjm');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('wbqkmrrvxn',0,0,'dpwtkaueap');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('rqenjhiqui',0,0,'adamgmaayi');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('mvvxpdxfbw',0,0,'lzzxuglknv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('chygloaaen',0,0,'zkxvjutsxq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dfjiiiyfgs',0,0,'dfcdawfhar');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('xwnpcsubua',0,0,'hmhcranztk');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('anwnfmocuq',0,0,'ekegjftnpz');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('sgdctbsbju',0,0,'zfoxrqevai');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jmqrazfuwm',0,0,'orrqlycygn');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('kenzgpfxeh',0,0,'sgixtmpclj');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dzhfrywduf',0,0,'sfmspznmim');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dnnowqeaxq',0,0,'piskmmjond');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('otgpeyiunz',0,0,'azivsvkjth');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dlfymfmgoh',0,0,'jfodpineww');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('bryrdvkfdp',0,0,'ropspwsdta');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dgtsdhnbed',0,0,'zdgjbfwcut');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('enoctilwap',0,0,'tgqhreeihr');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('uldkgdpimt',0,0,'xekexmrjxr');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('vjcgvkgczv',0,0,'oyakydnqwf');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('eudybxtazc',0,0,'shqwlgroyz');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ujvpbepqry',0,0,'fmuturkdtd');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('whumnalkhm',0,0,'oegtogpfkc');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('hrtjdgoibq',0,0,'annjazfcei');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ijrmxbjvff',0,0,'iblzbpugtq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('qggjzitgba',0,0,'mvblqbhgnm');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('urtbceztpt',0,0,'ccuefdmhyy');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('kdvgfivtkr',0,0,'gqphxrlqmw');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('khkwrbuvnz',0,0,'znlboqmteu');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('xfudmumenl',0,0,'ymwyeiajzz');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('sudtxpsmbf',0,0,'pqyetplucz');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('hmycinufqv',0,0,'dbmtxbrhiu');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('allehmfnmc',0,0,'vkcvzyersk');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gwcwgctvdm',0,0,'kswemftwvw');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('kphsflhggs',0,0,'wnqwmexuip');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('brczfbzina',0,0,'gvjkjdctyy');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('znjpbzfgbx',0,0,'clxqbffsyk');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('ziiekvzcyk',0,0,'xxqieheked');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('bvcfunvopv',0,0,'dasgkmfnrv');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('lxdihqyyin',0,0,'cmtwnnzxsb');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('xumyuwxeui',0,0,'qrjhsxftlf');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('snrtivzseu',0,0,'eybwxsdpgt');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gnmhcqitgm',0,0,'yilkmhnswe');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('kqusaweyys',0,0,'iomlwojdmw');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gjqoyqljha',0,0,'eobvvxfbeo');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gzcuhhgqph',0,0,'euymoffjun');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('jdwypzlniu',0,0,'ujmcnmewxn');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gyouxvgbic',0,0,'mkvmipasyd');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('lbcjqlqusk',0,0,'izwtrutzki');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('rcfihgdsoe',0,0,'ewgjbcpuin');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('dfjqssmrvf',0,0,'sdpspnurbi');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('knfbmesyyd',0,0,'cjfrtmqbgx');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('paivbarcak',0,0,'hmkvjybtcf');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('qiphuyuxno',0,0,'onmrqlgjfq');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('lpoiaohail',0,0,'tpabddgjfs');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('gcjsesbzvd',0,0,'aveqkbuwqh');
insert into Membership(MembershipType,NumberOfMembers,Discount,Benefits) values('kporcpnhsd',0,0,'mrdspefwcf');
insert into Employee(AccountID,Salary,isSalaryCredited) values(1,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(2,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(3,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(4,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(5,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(6,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(7,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(8,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(9,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(10,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(11,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(12,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(13,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(14,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(15,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(16,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(17,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(18,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(19,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(20,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(21,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(22,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(23,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(24,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(25,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(26,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(27,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(28,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(29,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(30,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(31,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(32,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(33,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(34,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(35,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(36,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(37,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(38,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(39,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(40,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(41,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(42,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(43,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(44,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(45,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(46,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(47,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(48,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(49,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(50,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(51,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(52,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(53,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(54,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(55,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(56,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(57,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(58,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(59,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(60,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(61,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(62,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(63,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(64,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(65,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(66,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(67,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(68,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(69,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(70,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(71,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(72,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(73,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(74,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(75,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(76,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(77,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(78,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(79,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(80,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(81,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(82,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(83,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(84,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(85,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(86,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(87,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(88,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(89,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(90,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(91,0,0);
insert into Employee(AccountID,Salary,isSalaryCredited) values(92,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(93,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(94,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(95,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(96,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(97,1,'2023-02-10','2024-02-10');
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(98,1,'2023-02-10','2024-02-10');
insert into Employee(AccountID,Salary,isSalaryCredited) values(99,0,0);
insert into Users(AccountID,MembershipID,MembershipStartDate,MembershipEndDate) values(100,1,'2023-02-10','2024-02-10');
insert into Tag(TagName) values('tfdxzdkzio');
insert into Tag(TagName) values('ruxurcrpxe');
insert into Tag(TagName) values('djsxshqjzz');
insert into Tag(TagName) values('jzedlyelmd');
insert into Tag(TagName) values('mpaenvanqm');
insert into Tag(TagName) values('riwdkvrkxv');
insert into Tag(TagName) values('yrhbsqqlic');
insert into Tag(TagName) values('vaphpdxqmy');
insert into Tag(TagName) values('hnvuhcevyj');
insert into Tag(TagName) values('ugawisxtbv');
insert into Tag(TagName) values('uohyyvvgzf');
insert into Tag(TagName) values('vgexanaydi');
insert into Tag(TagName) values('lfcbczuiny');
insert into Tag(TagName) values('thzmixrfmd');
insert into Tag(TagName) values('owsfhejfil');
insert into Tag(TagName) values('hgvvloopcr');
insert into Tag(TagName) values('jpempcmyhv');
insert into Tag(TagName) values('cwmtrxukla');
insert into Tag(TagName) values('fyxlopfacz');
insert into Tag(TagName) values('cyvzkilhud');
insert into Tag(TagName) values('soiuwwhlkp');
insert into Tag(TagName) values('dhmglekpir');
insert into Tag(TagName) values('nvdwqdjkbq');
insert into Tag(TagName) values('qacvijfznm');
insert into Tag(TagName) values('hadnvyxsru');
insert into Tag(TagName) values('yfytxqjbfm');
insert into Tag(TagName) values('hngjyjxtem');
insert into Tag(TagName) values('yyhgtfoojg');
insert into Tag(TagName) values('yzctmhfwqy');
insert into Tag(TagName) values('iymyfgybnq');
insert into Tag(TagName) values('mknyhdjgqv');
insert into Tag(TagName) values('ywcghqpmrc');
insert into Tag(TagName) values('ikmhjkzbzu');
insert into Tag(TagName) values('penckguwsv');
insert into Tag(TagName) values('hhqngkbhhp');
insert into Tag(TagName) values('nnyhembjvs');
insert into Tag(TagName) values('laaughdobw');
insert into Tag(TagName) values('avplawkmbr');
insert into Tag(TagName) values('hdxfxlerkv');
insert into Tag(TagName) values('pdxzinubsx');
insert into Tag(TagName) values('bdmevglqwd');
insert into Tag(TagName) values('srtzfderqx');
insert into Tag(TagName) values('iwfrmtfoto');
insert into Tag(TagName) values('xtkyngtttn');
insert into Tag(TagName) values('kykapbegzh');
insert into Tag(TagName) values('uctrihlqfz');
insert into Tag(TagName) values('fqgwxjhyww');
insert into Tag(TagName) values('vqvyervqmw');
insert into Tag(TagName) values('vmtohqgyox');
insert into Tag(TagName) values('psnicrjzcn');
insert into Tag(TagName) values('qndbluxevm');
insert into Tag(TagName) values('kigbptcrns');
insert into Tag(TagName) values('nehjpvqhvv');
insert into Tag(TagName) values('qymycevlvv');
insert into Tag(TagName) values('denadbnowu');
insert into Tag(TagName) values('qextspznqa');
insert into Tag(TagName) values('bacnsjjecw');
insert into Tag(TagName) values('mhpyxmiebn');
insert into Tag(TagName) values('stvsvmxjtm');
insert into Tag(TagName) values('tcpkyfstfn');
insert into Tag(TagName) values('rfaoprtwpr');
insert into Tag(TagName) values('qdnxmmrtpd');
insert into Tag(TagName) values('uwbkzzwyqp');
insert into Tag(TagName) values('zbbimstdmv');
insert into Tag(TagName) values('bpzhvekkyf');
insert into Tag(TagName) values('odoamlsriq');
insert into Tag(TagName) values('owzgxahcvj');
insert into Tag(TagName) values('twwcnqzpvc');
insert into Tag(TagName) values('xlpfrgvbyy');
insert into Tag(TagName) values('zhvlrwenaz');
insert into Tag(TagName) values('fuwjlqlfsx');
insert into Tag(TagName) values('isvnthsrey');
insert into Tag(TagName) values('xoyalvsiyy');
insert into Tag(TagName) values('jgwqpkufjt');
insert into Tag(TagName) values('fmisdijsxl');
insert into Tag(TagName) values('ihfqxkdhqp');
insert into Tag(TagName) values('qyombrhrby');
insert into Tag(TagName) values('ebzbknahkj');
insert into Tag(TagName) values('giliqjlheh');
insert into Tag(TagName) values('wwcttsbqsj');
insert into Tag(TagName) values('szaukuppgd');
insert into Tag(TagName) values('gtmwlaazfo');
insert into Tag(TagName) values('zlxvpmnong');
insert into Tag(TagName) values('dxrvqdhciq');
insert into Tag(TagName) values('scmlxiptzw');
insert into Tag(TagName) values('prwjqyxhvl');
insert into Tag(TagName) values('othuatxufz');
insert into Tag(TagName) values('ixnwehbwme');
insert into Tag(TagName) values('jbsqkhbkiw');
insert into Tag(TagName) values('handkqzzdl');
insert into Tag(TagName) values('bxdcoghpsk');
insert into Tag(TagName) values('ljasgutkdk');
insert into Tag(TagName) values('hvmksytmnf');
insert into Tag(TagName) values('rczhfgzazd');
insert into Tag(TagName) values('ptmevqhidr');
insert into Tag(TagName) values('mnqntbeetv');
insert into Tag(TagName) values('djvsxovmrr');
insert into Tag(TagName) values('usoiofuhkr');
insert into Tag(TagName) values('riapooabcs');
insert into Tag(TagName) values('qpxuqljbed');
insert into Category(Name,Tag1,Tag2,Tag3) values('wiowwndzob',1,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('luirpuwuhf',2,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zwpptkohgi',3,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('qmibujoonc',4,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nlxdzcmokk',5,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('edxbrkqily',6,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('pyououxwlm',7,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('sywsgrbskg',8,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ghmnxoanji',9,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ptqmfmowcn',10,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('barbqhgozy',11,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('jfawibdzcy',12,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wdqbepnbtf',13,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('qehowxajxr',14,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('qmsosiwujo',15,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('hryiqefifi',16,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('tlrkncclut',17,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('kumjfvaujz',18,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('chyoqhyfbb',19,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ukzjpdharb',20,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('saucxkvfga',21,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('bozvotvfpm',22,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('fxekxxzmxz',23,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('fiejodcdvl',24,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('mairwmaufj',25,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ekxclvrzhq',26,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('uxyxuurvgv',27,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('dhrxersjtu',28,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('dmobqqnoch',29,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ttprztjpln',30,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zlobyqoofq',31,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('jyhwiqoaex',32,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ivpwjaehai',33,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wvawqttmjf',34,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('inwkbtxhwc',35,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('rggryvkryx',36,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('chnzqvfoxo',37,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wibyvmhpns',38,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('cyjobsicem',39,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('sauosuplkq',40,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('vbtgwehhvj',41,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('brgzrxyeqq',42,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('sydhumasgw',43,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('piubgqyvah',44,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('jrnrgvtcjw',45,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('lxktesdfnu',46,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nfogrdwjhx',47,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nxjangqxxr',48,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('qhmqtexhjc',49,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('znrsbxpeqk',50,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('vwdavgmocd',51,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('izwllagiez',52,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('aaancubfmb',53,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('pxkjrunhpk',54,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('aptvdoigkx',55,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nynpwhypae',56,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('bhnnfvbbln',57,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('usrqecjnic',58,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nnphmbsvci',59,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zeauzmxdmg',60,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('sbmubztxdm',61,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('imlpxnmvag',62,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ycopeoqjxm',63,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zxnlbqgeit',64,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('mfwsmfaite',65,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nkmsufrdzs',66,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('bfeovjxmaw',67,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('jfpkjundez',68,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('frywzkxzfq',69,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('gbnrvsrspn',70,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('nqozezmqgk',71,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('fvaafcetwx',72,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('higgpfcufo',73,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('dkczymjffn',74,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zdtpedccea',75,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('egnxaagjxd',76,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('dxcsldsjud',77,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wtkpzklvph',78,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ltsbyicvff',79,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('leiquddmzp',80,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('evpxpjheqy',81,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('vieqyrzcbr',82,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('crjkhtrjdo',83,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ehzwceahai',84,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('gtmbblwotn',85,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('zykscbxowy',86,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('utxdanvmpr',87,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('hvcivjdiso',88,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('sominxtukf',89,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('oxuaveokvx',90,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('iwfbevsnwh',91,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('xbvbkwjtkd',92,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('ofoskjnqvh',93,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('utazavjyxg',94,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wrwiblglla',95,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('fedtklmppz',96,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('wcglpzggle',97,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('mokyfmzpqv',98,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('gofvyqkwwi',99,NULL,NULL);
insert into Category(Name,Tag1,Tag2,Tag3) values('uiauuknqzy',100,NULL,NULL);
insert into Discount(MembershipID,CategoryID,Percentage) values(1,59,44);
insert into Discount(MembershipID,CategoryID,Percentage) values(2,15,93);
insert into Discount(MembershipID,CategoryID,Percentage) values(3,54,57);
insert into Discount(MembershipID,CategoryID,Percentage) values(4,92,85);
insert into Discount(MembershipID,CategoryID,Percentage) values(5,61,1);
insert into Discount(MembershipID,CategoryID,Percentage) values(6,67,2);
insert into Discount(MembershipID,CategoryID,Percentage) values(7,40,21);
insert into Discount(MembershipID,CategoryID,Percentage) values(8,50,31);
insert into Discount(MembershipID,CategoryID,Percentage) values(9,41,19);
insert into Discount(MembershipID,CategoryID,Percentage) values(10,10,56);
insert into Discount(MembershipID,CategoryID,Percentage) values(11,14,21);
insert into Discount(MembershipID,CategoryID,Percentage) values(12,81,27);
insert into Discount(MembershipID,CategoryID,Percentage) values(13,1,90);
insert into Discount(MembershipID,CategoryID,Percentage) values(14,1,18);
insert into Discount(MembershipID,CategoryID,Percentage) values(15,100,95);
insert into Discount(MembershipID,CategoryID,Percentage) values(16,25,94);
insert into Discount(MembershipID,CategoryID,Percentage) values(17,71,19);
insert into Discount(MembershipID,CategoryID,Percentage) values(18,80,18);
insert into Discount(MembershipID,CategoryID,Percentage) values(19,21,75);
insert into Discount(MembershipID,CategoryID,Percentage) values(20,34,39);
insert into Discount(MembershipID,CategoryID,Percentage) values(21,6,63);
insert into Discount(MembershipID,CategoryID,Percentage) values(22,25,1);
insert into Discount(MembershipID,CategoryID,Percentage) values(23,81,100);
insert into Discount(MembershipID,CategoryID,Percentage) values(24,7,10);
insert into Discount(MembershipID,CategoryID,Percentage) values(25,46,95);
insert into Discount(MembershipID,CategoryID,Percentage) values(26,77,6);
insert into Discount(MembershipID,CategoryID,Percentage) values(27,49,9);
insert into Discount(MembershipID,CategoryID,Percentage) values(28,86,97);
insert into Discount(MembershipID,CategoryID,Percentage) values(29,16,54);
insert into Discount(MembershipID,CategoryID,Percentage) values(30,63,11);
insert into Discount(MembershipID,CategoryID,Percentage) values(31,52,64);
insert into Discount(MembershipID,CategoryID,Percentage) values(32,34,98);
insert into Discount(MembershipID,CategoryID,Percentage) values(33,70,50);
insert into Discount(MembershipID,CategoryID,Percentage) values(34,84,5);
insert into Discount(MembershipID,CategoryID,Percentage) values(35,63,63);
insert into Discount(MembershipID,CategoryID,Percentage) values(36,26,36);
insert into Discount(MembershipID,CategoryID,Percentage) values(37,93,41);
insert into Discount(MembershipID,CategoryID,Percentage) values(38,72,84);
insert into Discount(MembershipID,CategoryID,Percentage) values(39,15,1);
insert into Discount(MembershipID,CategoryID,Percentage) values(40,16,48);
insert into Discount(MembershipID,CategoryID,Percentage) values(41,27,100);
insert into Discount(MembershipID,CategoryID,Percentage) values(42,78,7);
insert into Discount(MembershipID,CategoryID,Percentage) values(43,12,35);
insert into Discount(MembershipID,CategoryID,Percentage) values(44,49,61);
insert into Discount(MembershipID,CategoryID,Percentage) values(45,41,8);
insert into Discount(MembershipID,CategoryID,Percentage) values(46,62,70);
insert into Discount(MembershipID,CategoryID,Percentage) values(47,89,34);
insert into Discount(MembershipID,CategoryID,Percentage) values(48,14,31);
insert into Discount(MembershipID,CategoryID,Percentage) values(49,35,52);
insert into Discount(MembershipID,CategoryID,Percentage) values(50,10,76);
insert into Discount(MembershipID,CategoryID,Percentage) values(51,32,4);
insert into Discount(MembershipID,CategoryID,Percentage) values(52,77,77);
insert into Discount(MembershipID,CategoryID,Percentage) values(53,83,85);
insert into Discount(MembershipID,CategoryID,Percentage) values(54,92,16);
insert into Discount(MembershipID,CategoryID,Percentage) values(55,17,85);
insert into Discount(MembershipID,CategoryID,Percentage) values(56,62,59);
insert into Discount(MembershipID,CategoryID,Percentage) values(57,95,2);
insert into Discount(MembershipID,CategoryID,Percentage) values(58,42,72);
insert into Discount(MembershipID,CategoryID,Percentage) values(59,66,10);
insert into Discount(MembershipID,CategoryID,Percentage) values(60,26,94);
insert into Discount(MembershipID,CategoryID,Percentage) values(61,4,27);
insert into Discount(MembershipID,CategoryID,Percentage) values(62,37,30);
insert into Discount(MembershipID,CategoryID,Percentage) values(63,29,89);
insert into Discount(MembershipID,CategoryID,Percentage) values(64,42,30);
insert into Discount(MembershipID,CategoryID,Percentage) values(65,96,64);
insert into Discount(MembershipID,CategoryID,Percentage) values(66,60,46);
insert into Discount(MembershipID,CategoryID,Percentage) values(67,7,1);
insert into Discount(MembershipID,CategoryID,Percentage) values(68,81,22);
insert into Discount(MembershipID,CategoryID,Percentage) values(69,74,73);
insert into Discount(MembershipID,CategoryID,Percentage) values(70,72,15);
insert into Discount(MembershipID,CategoryID,Percentage) values(71,54,75);
insert into Discount(MembershipID,CategoryID,Percentage) values(72,67,93);
insert into Discount(MembershipID,CategoryID,Percentage) values(73,41,20);
insert into Discount(MembershipID,CategoryID,Percentage) values(74,94,100);
insert into Discount(MembershipID,CategoryID,Percentage) values(75,33,46);
insert into Discount(MembershipID,CategoryID,Percentage) values(76,91,61);
insert into Discount(MembershipID,CategoryID,Percentage) values(77,7,23);
insert into Discount(MembershipID,CategoryID,Percentage) values(78,98,3);
insert into Discount(MembershipID,CategoryID,Percentage) values(79,34,65);
insert into Discount(MembershipID,CategoryID,Percentage) values(80,68,83);
insert into Discount(MembershipID,CategoryID,Percentage) values(81,60,56);
insert into Discount(MembershipID,CategoryID,Percentage) values(82,59,85);
insert into Discount(MembershipID,CategoryID,Percentage) values(83,15,75);
insert into Discount(MembershipID,CategoryID,Percentage) values(84,56,7);
insert into Discount(MembershipID,CategoryID,Percentage) values(85,21,37);
insert into Discount(MembershipID,CategoryID,Percentage) values(86,100,68);
insert into Discount(MembershipID,CategoryID,Percentage) values(87,68,86);
insert into Discount(MembershipID,CategoryID,Percentage) values(88,68,74);
insert into Discount(MembershipID,CategoryID,Percentage) values(89,69,22);
insert into Discount(MembershipID,CategoryID,Percentage) values(90,46,16);
insert into Discount(MembershipID,CategoryID,Percentage) values(91,84,30);
insert into Discount(MembershipID,CategoryID,Percentage) values(92,62,90);
insert into Discount(MembershipID,CategoryID,Percentage) values(93,99,52);
insert into Discount(MembershipID,CategoryID,Percentage) values(94,28,41);
insert into Discount(MembershipID,CategoryID,Percentage) values(95,13,75);
insert into Discount(MembershipID,CategoryID,Percentage) values(96,56,71);
insert into Discount(MembershipID,CategoryID,Percentage) values(97,53,21);
insert into Discount(MembershipID,CategoryID,Percentage) values(98,68,50);
insert into Discount(MembershipID,CategoryID,Percentage) values(99,77,16);
insert into Discount(MembershipID,CategoryID,Percentage) values(100,28,11);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ekjipkicqe',224,'j p z m x t n l c g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ofowxtztmx',835,'t c w y m n c e k i',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'orzvhhtjzo',161,'u u h e p y c h o f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'qrztttbizk',845,'z w b v t c v x e n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'efhnxucave',547,'f h f z m x n p m h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zwihhzpfdl',766,'t l x w d s w k e f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'crndzjxbwr',988,'e x i s h o a l m l',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'sghnwpilsf',431,'c x s m t h b b s n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'cpafiomrxb',142,'d j g b o k k c c f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'hgwndolntz',151,'o d k a v f u e r n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'iqluwhcfzy',790,'f s e v d v s g u m',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'wpkdtzynum',935,'g r i z c u h p b g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zlniylonps',922,'i c d v p a u n n a',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ssilogziiq',103,'x t n q a e v f j e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zhkehzcoqc',185,'a k u f c f q s p w',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'lzofwruqmb',140,'w c r s y p k g i u',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xtynhzmnhk',106,'l h l i u q h j z p',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'jgzvwrrqrt',125,'s y b s r y r o o b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'qksxsiumhq',749,'t f j q s g p z h j',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'pbsmvlzgqi',639,'y y z t o n t o k f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xrziggricq',365,'c q a l d m h z u h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'nymbgfqyvz',887,'s k v d x c y m u i',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'gmnahzitli',338,'z l n p p m g k x r',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'focaxfsaiw',228,'l z w g z l f m g f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'mhxsyxmkyu',750,'f x u d b f d t c a',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'dhubzszyug',706,'n u d x s r p n b c',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xckttjlcct',388,'m j r u m h c t r k',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'gmkpwdaada',999,'b m m i m h s f j e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'znvivhmgpz',935,'b s s c r n q h r k',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'jlgchqjzqu',944,'l f d p q q f q h x',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'lwkmectgdl',265,'b x q x b d l o m y',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zcvfkosemb',640,'j w a m x f t e w b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'fkowogjyne',107,'s s v v e p q z g e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xxflhmcaew',666,'v d p w o a i f c v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'bcdxcpqibo',570,'i s u s u l r l g k',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'letswidqox',902,'v j t f w l b z o h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'hyvtugofqr',286,'a u z s m p p k z l',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'trctwdnuay',906,'a p a s b g z y z c',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'hdtrarfjzk',415,'w l i b e o x e n q',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'gppmnopzvv',187,'u k a k d v s z w u',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'jcsjvkidnj',987,'m h t f m l v s q d',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'puhxnxwscc',803,'m d b l z b g o m n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'wlwwtmadxo',500,'c p r c j s x n a f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'yuczvrfmbt',684,'f h y u i p p u x j',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'kpqgdkpcyi',791,'s r e c v k b q e i',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zozvhougdl',959,'e w q q a m a y j d',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'yljvefxjyb',282,'w l p o r b a c x p',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ydgaojnogm',561,'m k s u v i y d g v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ijnxpruygv',325,'o q q r j m x h t n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zdkinzklmv',311,'v y f v i y r m s b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'aoxpajlygg',645,'d t a z v t j p f g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'dahbxympzr',223,'j t a r y g i z o r',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'dugswmhvxd',795,'z b h o x e z c g x',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'vrzjrqgacm',279,'e q r o q y p u m h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'sdzuhgwcaz',175,'d q y x q y m m o m',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'krxramifpl',649,'c w c v k a d i r h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'usbvxuhgnu',698,'w l r a p w n d g l',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'lferyfdqcp',588,'d e v z g o q t d i',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'vdybhdxcfi',699,'x p y e s q p r r v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'muvytuphwm',136,'o b j p f x s k z v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'exncloacfl',438,'g f a z g n a x j p',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'kubesxjthl',865,'v d i i c n f o s r',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ikrgzyglrc',364,'b v i r x m y u x z',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'fepfkqssma',822,'y v n k z i y a j e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'iqddqhlgae',793,'r x d n d y o t h m',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'owuedwzsdv',955,'h d a y u e l j n u',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xfayzepfhd',258,'e j p e r h q l w t',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ssiyggrepp',416,'y j l v g d g l x e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'vojrdorpri',950,'f d h d i j m l p d',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zkadcndwjh',138,'r j h d z z m q x f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'rkdrtgttfb',643,'x g u e u a c i y j',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'lfduklacsr',343,'d a v x i e n p d x',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'liewjrvyeo',188,'g a f e p y w f i q',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'uqgpcrwupk',760,'r e d o p u u q a o',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'veblezgmkc',989,'g n q j j r g z l k',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ncosgymskq',857,'z g r k f n z l a j',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'dvikdnajwa',594,'f g o j b j b i b u',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'tufghdkhvd',958,'u j p p m x z z t i',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'nytlbihyhy',409,'v o f y f g z x y u',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'wvkhqtewzg',532,'w u x c p u t k d b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ajsexxejie',948,'l l j r y r i y v a',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'axjjquazxw',142,'i d w n u t n m q v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'cuzbmkwrbv',116,'y a p b r y x a b b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'mcyxwphkyb',639,'z r h c h c c p z w',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'vykwmsvvyn',996,'g a y a m i b g k g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'kniqlxnmgj',896,'v q i w c b r h v n',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'vsvuvtuufr',183,'y d b s d q w o c e',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'uvcykyktlf',531,'e g c p t d f y k f',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'bcoxdpprux',543,'t y t r b s z x k y',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'krcpcoduqv',258,'s t u o t a z k b l',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'bzzcnhcplk',816,'l u s j k m s c w t',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'wceiplypkx',610,'t h c r v b h g m r',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'zyxqkycddo',198,'y n i i j w l t b g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'dqypnejgay',305,'d u v p a v a o d v',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'mwadnsvsyx',619,'m p f j b z k n m b',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'bajdaeqpmc',488,'v a v z a t n w a o',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'pceckticoh',517,'b q v d d t x x a g',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'jvzoisunpt',266,'s d d j c z m i r h',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'xgimdvllto',833,'j a r d o j v m b a',0,0,0,NULL,NULL,NULL);
insert into Product(CategoryID,Name,Cost,Description,Discount,Rating,Quantity,Tag1,Tag2,Tag3) values(1,'ngbghsrcfb',888,'j o g p f g d z z u',0,0,0,NULL,NULL,NULL);
insert into Review(ProductID,Rating,Content) values(1,0,'y j h d x x j j q t');
insert into Review(ProductID,Rating,Content) values(1,0,'j f n f q y h m n r');
insert into Review(ProductID,Rating,Content) values(1,0,'y b f u p l p s j i');
insert into Review(ProductID,Rating,Content) values(1,0,'i h h n y l r o v n');
insert into Review(ProductID,Rating,Content) values(1,0,'i h q z z o h b x m');
insert into Review(ProductID,Rating,Content) values(1,0,'e n n l u r r t e u');
insert into Review(ProductID,Rating,Content) values(1,0,'d r b v g x i d e v');
insert into Review(ProductID,Rating,Content) values(1,0,'h e r g g t b y u s');
insert into Review(ProductID,Rating,Content) values(1,0,'p o i r p g e f n j');
insert into Review(ProductID,Rating,Content) values(1,0,'j u b q b l p e x x');
insert into Review(ProductID,Rating,Content) values(1,0,'e f i b t e k x h c');
insert into Review(ProductID,Rating,Content) values(1,0,'b e x h v z n e m z');
insert into Review(ProductID,Rating,Content) values(1,0,'w k o z k v r c a v');
insert into Review(ProductID,Rating,Content) values(1,0,'r k h s h z c z s g');
insert into Review(ProductID,Rating,Content) values(1,0,'w g r j m o n a t r');
insert into Review(ProductID,Rating,Content) values(1,0,'x n s h a d e d m o');
insert into Review(ProductID,Rating,Content) values(1,0,'c c a b c b t s j r');
insert into Review(ProductID,Rating,Content) values(1,0,'k j t k s a r m n n');
insert into Review(ProductID,Rating,Content) values(1,0,'l w u h j n i x o r');
insert into Review(ProductID,Rating,Content) values(1,0,'k f h r y p l f v m');
insert into Review(ProductID,Rating,Content) values(1,0,'e l f l b h b n v q');
insert into Review(ProductID,Rating,Content) values(1,0,'w u c l h e l p k z');
insert into Review(ProductID,Rating,Content) values(1,0,'z z h u u p q b r b');
insert into Review(ProductID,Rating,Content) values(1,0,'d n e f f y v g s j');
insert into Review(ProductID,Rating,Content) values(1,0,'m z n j s b o l u f');
insert into Review(ProductID,Rating,Content) values(1,0,'q o m a r g h s t k');
insert into Review(ProductID,Rating,Content) values(1,0,'a y h e q p r m g l');
insert into Review(ProductID,Rating,Content) values(1,0,'l b s g u j c m y n');
insert into Review(ProductID,Rating,Content) values(1,0,'m x l s w h x f e q');
insert into Review(ProductID,Rating,Content) values(1,0,'a g s f b p k f q l');
insert into Review(ProductID,Rating,Content) values(1,0,'h i l y w z x e c w');
insert into Review(ProductID,Rating,Content) values(1,0,'c r u p e z m r j b');
insert into Review(ProductID,Rating,Content) values(1,0,'e d s g x r v c d l');
insert into Review(ProductID,Rating,Content) values(1,0,'l h w y l s g m m t');
insert into Review(ProductID,Rating,Content) values(1,0,'f c p n w w a v i s');
insert into Review(ProductID,Rating,Content) values(1,0,'g b p h h z f b f x');
insert into Review(ProductID,Rating,Content) values(1,0,'c n q y v b v h j j');
insert into Review(ProductID,Rating,Content) values(1,0,'g v d m h v c q h n');
insert into Review(ProductID,Rating,Content) values(1,0,'n z q p g o q f m p');
insert into Review(ProductID,Rating,Content) values(1,0,'s u w j s x e s c f');
insert into Review(ProductID,Rating,Content) values(1,0,'c g g i n m a w o e');
insert into Review(ProductID,Rating,Content) values(1,0,'p p t x x w j j w b');
insert into Review(ProductID,Rating,Content) values(1,0,'g q v n i q f f x x');
insert into Review(ProductID,Rating,Content) values(1,0,'m d t p s l y f j k');
insert into Review(ProductID,Rating,Content) values(1,0,'n c d u q o d v t d');
insert into Review(ProductID,Rating,Content) values(1,0,'m n n m p f c b y n');
insert into Review(ProductID,Rating,Content) values(1,0,'x h h g h o j p d u');
insert into Review(ProductID,Rating,Content) values(1,0,'o v g n o r d e l j');
insert into Review(ProductID,Rating,Content) values(1,0,'q r o l t x q u h j');
insert into Review(ProductID,Rating,Content) values(1,0,'h a z j j i d d w w');
insert into Review(ProductID,Rating,Content) values(1,0,'v q x b f e r i z i');
insert into Review(ProductID,Rating,Content) values(1,0,'r f w r b i s k v r');
insert into Review(ProductID,Rating,Content) values(1,0,'l q b n m o e h j g');
insert into Review(ProductID,Rating,Content) values(1,0,'m k z k k s w x j n');
insert into Review(ProductID,Rating,Content) values(1,0,'n o x s b i d x e c');
insert into Review(ProductID,Rating,Content) values(1,0,'n x l y e z q p p o');
insert into Review(ProductID,Rating,Content) values(1,0,'l d g u y g m b p j');
insert into Review(ProductID,Rating,Content) values(1,0,'e f r o t n w n e w');
insert into Review(ProductID,Rating,Content) values(1,0,'x y i z x w m s m g');
insert into Review(ProductID,Rating,Content) values(1,0,'i s q o b r r h j y');
insert into Review(ProductID,Rating,Content) values(1,0,'q z h v a e e t u k');
insert into Review(ProductID,Rating,Content) values(1,0,'j f p w g u w u z s');
insert into Review(ProductID,Rating,Content) values(1,0,'e z k r s t x s b b');
insert into Review(ProductID,Rating,Content) values(1,0,'g m n d m a c b u k');
insert into Review(ProductID,Rating,Content) values(1,0,'a v o n d y h f z e');
insert into Review(ProductID,Rating,Content) values(1,0,'d y y n t w w d l f');
insert into Review(ProductID,Rating,Content) values(1,0,'e h r c h q r u s z');
insert into Review(ProductID,Rating,Content) values(1,0,'z w o w g v e g k n');
insert into Review(ProductID,Rating,Content) values(1,0,'j u n p h n s c b k');
insert into Review(ProductID,Rating,Content) values(1,0,'a v f g f y s t f e');
insert into Review(ProductID,Rating,Content) values(1,0,'c d l g k a f b b w');
insert into Review(ProductID,Rating,Content) values(1,0,'i t s l y h e c l z');
insert into Review(ProductID,Rating,Content) values(1,0,'x h h o x m r q b y');
insert into Review(ProductID,Rating,Content) values(1,0,'z w m n l h h s a x');
insert into Review(ProductID,Rating,Content) values(1,0,'m g u k w v e y x f');
insert into Review(ProductID,Rating,Content) values(1,0,'v e l p s u n x e a');
insert into Review(ProductID,Rating,Content) values(1,0,'o r k z m m i m i m');
insert into Review(ProductID,Rating,Content) values(1,0,'g w x g s d f b z g');
insert into Review(ProductID,Rating,Content) values(1,0,'g h n m q l x p v w');
insert into Review(ProductID,Rating,Content) values(1,0,'m w o r f c v a u a');
insert into Review(ProductID,Rating,Content) values(1,0,'f g o p x p b a i k');
insert into Review(ProductID,Rating,Content) values(1,0,'f l k e b j p u h s');
insert into Review(ProductID,Rating,Content) values(1,0,'w p i o m c v p q p');
insert into Review(ProductID,Rating,Content) values(1,0,'n x f b z b c w b b');
insert into Review(ProductID,Rating,Content) values(1,0,'i z k g q y s h c j');
insert into Review(ProductID,Rating,Content) values(1,0,'c y u t f c l m w e');
insert into Review(ProductID,Rating,Content) values(1,0,'r t s g l j f q v f');
insert into Review(ProductID,Rating,Content) values(1,0,'w l r m o j r h d b');
insert into Review(ProductID,Rating,Content) values(1,0,'l w n n y q a i n v');
insert into Review(ProductID,Rating,Content) values(1,0,'p m a d b m a t t q');
insert into Review(ProductID,Rating,Content) values(1,0,'v n b h n g w c e h');
insert into Review(ProductID,Rating,Content) values(1,0,'b g r m u i g t o s');
insert into Review(ProductID,Rating,Content) values(1,0,'a r e z e e v v i b');
insert into Review(ProductID,Rating,Content) values(1,0,'u f t k g a o q d e');
insert into Review(ProductID,Rating,Content) values(1,0,'n n o k a r k n w k');
insert into Review(ProductID,Rating,Content) values(1,0,'l b p g f s l x c u');
insert into Review(ProductID,Rating,Content) values(1,0,'e u n o r o l e b j');
insert into Review(ProductID,Rating,Content) values(1,0,'c t e x e n n s v t');
insert into Review(ProductID,Rating,Content) values(1,0,'k m t l q k c s h p');
insert into Review(ProductID,Rating,Content) values(1,0,'o r e x g a w x t h');
insert into CartItem(SessionID,ProductID,Quantity) values(1,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(2,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(3,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(4,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(5,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(6,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(7,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(8,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(9,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(10,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(11,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(12,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(13,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(14,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(15,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(16,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(17,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(18,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(19,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(20,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(21,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(22,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(23,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(24,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(25,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(26,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(27,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(28,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(29,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(30,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(31,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(32,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(33,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(34,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(35,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(36,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(37,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(38,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(39,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(40,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(41,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(42,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(43,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(44,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(45,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(46,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(47,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(48,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(49,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(50,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(51,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(52,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(53,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(54,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(55,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(56,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(57,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(58,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(59,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(60,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(61,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(62,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(63,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(64,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(65,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(66,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(67,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(68,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(69,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(70,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(71,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(72,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(73,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(74,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(75,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(76,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(77,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(78,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(79,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(80,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(81,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(82,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(83,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(84,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(85,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(86,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(87,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(88,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(89,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(90,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(91,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(92,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(93,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(94,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(95,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(96,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(97,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(98,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(99,1,1);
insert into CartItem(SessionID,ProductID,Quantity) values(100,1,1);
