# Generated by Django 4.1.7 on 2023-04-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("cost", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("discount", models.FloatField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("quantity", models.IntegerField()),
                (
                    "CategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("ReviewID", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=300)),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("TagID", models.AutoField(primary_key=True, serialize=False)),
                ("TagName", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.AddField(
            model_name="product",
            name="tag1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag1",
                to="core.tag",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tag2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag2",
                to="core.tag",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tag3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag3",
                to="core.tag",
            ),
        ),
    ]
